### ISSUE TITLE
common communications -Zeb- reply directly to this issue 

### ISSUE THREAD

**Issue by evewurtele** [arendsee/synder#4]
confirm everything you receive by replying to it directly (in this case, in github issues).  after the first few weeks we should have China-US communications figured out to a T.  

1. Pick a **single** repository to be communicating in so that the whole group can be aware of the various issues and progress. 
(core orphan/PMR group=Manhoi, Arun, Priyanka, Urminder, Jing, Ananth, Eve, Zeb)  (we should add  Kevin, Pramesh, Tianlong into the group after we get it going)
2. Zeb, each week report to the group what you have done, via the issues channel.  You can just reference code or whatever.  You are at the center of the orphan coding hub at present.

**Comment by arendsee** [comment]
I think Slack would be a better venue for this. I'll copy this issue into the `synder` channel in Slack. The issues of github are ideally reserved for bug reports, which should be resolved and closed quickly. A repository with issues that have been open for a long time looks like it isn't being maintained.

That said, bugs and feature requests specific to Synder absolutely belong in here.

**Comment by evewurtele** [comment]
good practice!

Eve Syrkin Wurtele, Professor     515-708-3232 (cell)  538 Science II,
Iowa State Univ.  homepage
<http://www.gdcb.iastate.edu/faculty-and-research/faculty/eve-syrkin-wurtele/>
Meta!Blast computer game <http://metablast.org/>    PMR Systems Biology
Resource <http://www.metnetdb.org/PMR/>   Publications
<http://www.ncbi.nlm.nih.gov/sites/myncbi/collections/public/1jMsIEbfU0gcCYtuh_aBiUdAs/?sort=date&direction=descending>

противный женщина
