### ISSUE TITLE
question in output

### ISSUE THREAD

**Issue by lijing28101** [arendsee/synder#5]
Hi @arendsee, I used the example ty1 data in your package. 
```search(ty1$syn$Saccharomyces_arboricola,ty1$gff)```
The score column in output is NA, and inbetween is FALSE.
I also tried to set the offset to 011111, and change the trans to d, but thees two column in the output are the same. Why it has no score?
And how to understand the last three column? What condition means the query gene has similar sequence in the target genome?

**Comment by arendsee** [comment]
So there are a couple points here, I'll address them one by one.

**1. `inbetween` is FALSE**

This is fine. It just means that every one of the intervals in the query set overlaps at least one interval on the query side of the synteny map. In the case of the of the ty1 dataset, all the intervals are yeast transposons, which likely map to many places in the target genome.

 **2. What is the meaning of the last three columns?**

First you can check the documentation with `?search`. I find it very hard to describe interval relationships in words. The ideas can be easily described with pictures. So what I really need is a little diagram in the vignette that shows examples of these cases. The `l_flag` and `r_flag` columns contain the following content for the left and right bounds of the interval: 
```
     0. bound is inside a syntenic interval
     1. bound is between intervals in a contiguous set
     2. bound does not overlap the contiguous set
     3. bound is beyond any syntenic interval (near end of scaffold)
```
You can think of the `l_flag` and `r_flag` as a pair that describes the reliability of the search interval. If the flags are (0,0) then the interval has cleanly defined, unambiguous, bounds. If the flags are (1,1), then the query doesn't overlap any intervals, but it is in a syntenically *quiet* location. If the flags are (2,2), then the search interval is in a *scrambled* location -- the genomes have rearanged and the location of the query's homolog is ambiguous. If the flags are (3,x), then the interval is near the end of a scaffold -- this may occur frequently in poorly assembled genomes.

The column `inbetween` means that the query interval doesn't overlap any synteny maps. Note that this is not the same as just `l_flag > 0` and `r_flag > 0`. These flags refer only to the bounds.

**3. The score is NaN**

Well, this is bad. I have a vague memory of noting this in the past, and thinking I should do something about it.

Don't bother changing the transforms and offsets, it won't fix the problem. I either have a NULL vector on the C++ side or am setting the column to NaN on the R side ... or something else strange. Not sure. I've spent some time looking over the code, but haven't found the problem yet.

I mark this as a bug and fix it as soon as possible.

**Comment by lijing28101** [comment]
![capture](https://user-images.githubusercontent.com/22349573/27495214-a028572e-5816-11e7-94cd-95f472bc3055.PNG)
![screenshot from 2017-06-23 13-18-01](https://user-images.githubusercontent.com/22349573/27495399-5d5445b0-5817-11e7-88b0-eef766023f81.png)

I choose a query interval ```S000006792``` to find its search intervals. The black boxes in these two species mean the syntenic map. The red box in the S.cerevisiae is the query interval, and four red boxes with blue outline in S.arboricola are search intervals. Why the search interval is not in the red```?```region according the figure in your manuscript? And why the ```l_flag``` and ```r_flag``` for these four SI are (2,0), (2,2) or (0,2)? ```0. bound is inside a syntenic interval``` 0 should in the black box, right? But only SI (152064,158090) has a little overlap with the black box, and the flag is (2,2). I'm also confused about ``` contiguous set```  There are 11 black boxes between the red boxes, do you mean these 11 black boxes could be grouped into different contiguous sets? Such as box 1,2,3 as a contiguous set, and box 2,3,4,5 also could be a contiguous set?

**Comment by arendsee** [comment]
A given pair from the synteny map is always assigned to exactly one contiguous set. Contiguous sets are sets of blocks that are adjacent both on the query and target sides. In the image you show above, there would be exactly one contiguous set. All the blocks have the same order on the target and query sides and do not overlap.

The query interval you show should indeed map to the region you marked with a `?` and the flags should be (1,1). I am fairly confident that `synder` maps correctly. You are *probably* misinterpreting the results, which indicates both a problem in my documentation and a lack of good visualization tools.

Can you send me the synteny map and interval that produced this result?

**Comment by lijing28101** [comment]
I just realized that your synteny map in R package is different from mine. And the result include + and - strand.  I can understand the result after I check the synteny map in R.

**Comment by arendsee** [comment]
Nice, good job finding the problem!
