### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by evewurtele** [arendsee/synder#7]
For a practical introduction to synder, read **introduction vignette.**      the intro link is broken

**Comment by arendsee** [comment]
Where is this link? I don't think I currently have a link to a vignette from the README. I made one in the past; perhaps you are on an old branch?

**Comment by evewurtele** [comment]
https://github.com/arendsee/synder/blob/cb67e7498c5d174a7a3f83cb1140be14b5cf1ca7/vignettes/algorithm.Rmd     it is here

**Comment by arendsee** [comment]
Ah, that is because you are reading the raw markdown vignette, not the compiled vignette. None of the plots or tables will render either. The links are relative to the directory where the compiled HTML vignettes are stored on the users computer. So they won't work on github.
