### ISSUE TITLE
Error in fetch(key)

### ISSUE THREAD

**Issue by weihuang12** [arendsee/synder#8]
In R studio
after install the synder package, click on 
Packages ->synder -> any of these as.data.frame.DumpResult, as.data.frame.GFF, etc. got
this error message 
Error in fetch(key) : lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/synder/help/synder.rdb' is corrupt

**Comment by arendsee** [comment]
Hi @weihuang12 , thanks for the report.

I don't use Rstudio and haven't encountered this specific error.

However, you might try looking at this question on stackoverflow: https://stackoverflow.com/questions/30424608/error-in-fetchkey-lazy-load-database

They recommend simply deleting the corrupt file: 
`/Library/Frameworks/R.framework/Versions/3.5/Resources/library/synder/help/synder.rdb`

And then restarting Rstudio.

**Comment by arendsee** [comment]
I'll close this question for now. @weihuang12 if the problem remains, you may reopen it.
