### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by asdcid** [arendsee/synder#9]
I tried to install synder with the suggestion, but it raised the error:

```
> library(devtools)
> install_github('arendsee/synder')
Downloading GitHub repo arendsee/synder@master
from URL https://api.github.com/repos/arendsee/synder/zipball/master
Installation failed: error in running command
```

Do you have any idea about that? 

Thanks
Raymond

**Comment by arendsee** [comment]
@asdcid Do you get the same problem when you install other github packages with `devtools`? For example:

``` R
devtools::install_github("tidyverse/dplyr")
```

You might check out [this issue](https://github.com/r-lib/devtools/issues/1722).

**Comment by asdcid** [comment]
Thanks. I solved this problem by reinstalled R.
